package com.isakaro.kwik.utils

import androidx.annotation.DrawableRes
import com.isakaro.kwik.R

val countryList = listOf(
    CountryInfo("Afghanistan", Country.AF, "+93", flag = R.drawable.af),
    CountryInfo("Åland Islands", Country.AX, "+358", flag = R.drawable.ax),
    CountryInfo("Albania", Country.AL, "+355", flag = R.drawable.al),
    CountryInfo("Algeria", Country.DZ, "+213", flag = R.drawable.dz),
    CountryInfo("American Samoa", Country.AS, "+1", flag = R.drawable.`as`),
    CountryInfo("Andorra", Country.AD, "+376", flag = R.drawable.ad),
    CountryInfo("Angola", Country.AO, "+244", flag = R.drawable.ao),
    CountryInfo("Anguilla", Country.AI, "+1", flag = R.drawable.ai),
    CountryInfo("Antarctica", Country.AQ, "+672", flag = R.drawable.aq),
    CountryInfo("Antigua and Barbuda", Country.AG, "+1", flag = R.drawable.ag),
    CountryInfo("Argentina", Country.AR, "+54", flag = R.drawable.ar),
    CountryInfo("Armenia", Country.AM, "+374", flag = R.drawable.am),
    CountryInfo("Aruba", Country.AW, "+297", flag = R.drawable.aw),
    CountryInfo("Australia", Country.AU, "+61", flag = R.drawable.au),
    CountryInfo("Austria", Country.AT, "+43", flag = R.drawable.at),
    CountryInfo("Azerbaijan", Country.AZ, "+994", flag = R.drawable.az),
    CountryInfo("Bahamas", Country.BS, "+1", flag = R.drawable.bs),
    CountryInfo("Bahrain", Country.BH, "+973", flag = R.drawable.bh),
    CountryInfo("Bangladesh", Country.BD, "+880", flag = R.drawable.bd),
    CountryInfo("Barbados", Country.BB, "+1", flag = R.drawable.bb),
    CountryInfo("Belarus", Country.BY, "+375", flag = R.drawable.by),
    CountryInfo("Belgium", Country.BE, "+32", flag = R.drawable.be),
    CountryInfo("Belize", Country.BZ, "+501", flag = R.drawable.bz),
    CountryInfo("Benin", Country.BJ, "+229", flag = R.drawable.bj),
    CountryInfo("Bermuda", Country.BM, "+1", flag = R.drawable.bm),
    CountryInfo("Bhutan", Country.BT, "+975", flag = R.drawable.bt),
    CountryInfo("Bolivia", Country.BO, "+591", flag = R.drawable.bo),
    CountryInfo("Bosnia and Herzegovina", Country.BA, "+387", flag = R.drawable.ba),
    CountryInfo("Botswana", Country.BW, "+267", flag = R.drawable.bw),
    CountryInfo("Bouvet Island", Country.BV, "+47", flag = R.drawable.bv),
    CountryInfo("Brazil", Country.BR, "+55", flag = R.drawable.br),
    CountryInfo("British Indian Ocean Territory", Country.IO, "+246", flag = R.drawable.io, tags = listOf("Chagos Islands")),
    CountryInfo("Brunei", Country.BN, "+673", flag = R.drawable.bn),
    CountryInfo("Bulgaria", Country.BG, "+359", flag = R.drawable.bg),
    CountryInfo("Burkina Faso", Country.BF, "+226", flag = R.drawable.bf),
    CountryInfo("Burundi", Country.BI, "+257", flag = R.drawable.bi),
    CountryInfo("Cambodia", Country.KH, "+855", flag = R.drawable.kh),
    CountryInfo("Cameroon", Country.CM, "+237", flag = R.drawable.cm),
    CountryInfo("Canada", Country.CA, "+1", flag = R.drawable.ca),
    CountryInfo("Cape Verde", Country.CV, "+238", flag = R.drawable.cv),
    CountryInfo("Cayman Islands", Country.KY, "+1", flag = R.drawable.ky),
    CountryInfo("Central African Republic", Country.CF, "+236", flag = R.drawable.cf, tags = listOf("CAR")),
    CountryInfo("Chad", Country.TD, "+235", flag = R.drawable.td),
    CountryInfo("Chile", Country.CL, "+56", flag = R.drawable.cl),
    CountryInfo("China", Country.CN, "+86", flag = R.drawable.cn),
    CountryInfo("Christmas Island", Country.CX, "+61", flag = R.drawable.cx),
    CountryInfo("Cocos (Keeling) Islands", Country.CC, "+61", flag = R.drawable.cc),
    CountryInfo("Colombia", Country.CO, "+57", flag = R.drawable.co),
    CountryInfo("Comoros", Country.KM, "+269", flag = R.drawable.km),
    CountryInfo("Congo, The Republic of the", Country.CG, "+242", flag = R.drawable.cg, tags = listOf("Brazzaville")),
    CountryInfo("Congo, The Democratic Republic of the", Country.CD, "+243", flag = R.drawable.cd, tags = listOf("DRC", "Kinshasa")),
    CountryInfo("Cook Islands", Country.CK, "+682", flag = R.drawable.ck),
    CountryInfo("Costa Rica", Country.CR, "+506", flag = R.drawable.cr),
    CountryInfo("Croatia", Country.HR, "+385", flag = R.drawable.hr),
    CountryInfo("Cuba", Country.CU, "+53", flag = R.drawable.cu),
    CountryInfo("Cyprus", Country.CY, "+357", flag = R.drawable.cy),
    CountryInfo("Czech Republic", Country.CZ, "+420", flag = R.drawable.cz),
    CountryInfo("Denmark", Country.DK, "+45", flag = R.drawable.dk),
    CountryInfo("Djibouti", Country.DJ, "+253", flag = R.drawable.dj),
    CountryInfo("Dominica", Country.DM, "+1", flag = R.drawable.dm),
    CountryInfo("Dominican Republic", Country.DO, "+1", flag = R.drawable.do_),
    CountryInfo("Ecuador", Country.EC, "+593", flag = R.drawable.ec),
    CountryInfo("Egypt", Country.EG, "+20", flag = R.drawable.eg),
    CountryInfo("El Salvador", Country.SV, "+503", flag = R.drawable.sv),
    CountryInfo("Equatorial Guinea", Country.GQ, "+240", flag = R.drawable.gq),
    CountryInfo("Eritrea", Country.ER, "+291", flag = R.drawable.er),
    CountryInfo("Estonia", Country.EE, "+372", flag = R.drawable.ee),
    CountryInfo("eSwatini", Country.SZ, "+268", flag = R.drawable.sz),
    CountryInfo("Ethiopia", Country.ET, "+251", flag = R.drawable.et),
    CountryInfo("Falkland Islands (Malvinas)", Country.FK, "+500", flag = R.drawable.fk),
    CountryInfo("Faroe Islands", Country.FO, "+298", flag = R.drawable.fo),
    CountryInfo("Fiji", Country.FJ, "+679", flag = R.drawable.fj),
    CountryInfo("Finland", Country.FI, "+358", flag = R.drawable.fi),
    CountryInfo("France", Country.FR, "+33", flag = R.drawable.fr),
    CountryInfo("French Guiana", Country.GF, "+594", flag = R.drawable.gf),
    CountryInfo("French Polynesia", Country.PF, "+689", flag = R.drawable.pf),
    CountryInfo("French Southern Territories", Country.TF, "+262", flag = R.drawable.tf),
    CountryInfo("Gabon", Country.GA, "+241", flag = R.drawable.ga),
    CountryInfo("Gambia", Country.GM, "+220", flag = R.drawable.gm),
    CountryInfo("Georgia", Country.GE, "+995", flag = R.drawable.ge),
    CountryInfo("Germany", Country.DE, "+49", flag = R.drawable.de, tags = listOf("Deutschland", "Federal Republic of Germany")),
    CountryInfo("Ghana", Country.GH, "+233", flag = R.drawable.gh),
    CountryInfo("Gibraltar", Country.GI, "+350", flag = R.drawable.gi),
    CountryInfo("Greece", Country.GR, "+30", flag = R.drawable.gr),
    CountryInfo("Greenland", Country.GL, "+299", flag = R.drawable.gl),
    CountryInfo("Grenada", Country.GD, "+1", flag = R.drawable.gd),
    CountryInfo("Guadeloupe", Country.GP, "+590", flag = R.drawable.gp),
    CountryInfo("Guam", Country.GU, "+1", flag = R.drawable.gu),
    CountryInfo("Guatemala", Country.GT, "+502", flag = R.drawable.gt),
    CountryInfo("Guernsey", Country.GG, "+44", flag = R.drawable.gg),
    CountryInfo("Guinea", Country.GN, "+224", flag = R.drawable.gn),
    CountryInfo("Guinea-Bissau", Country.GW, "+245", flag = R.drawable.gw),
    CountryInfo("Guyana", Country.GY, "+592", flag = R.drawable.gy),
    CountryInfo("Haiti", Country.HT, "+509", flag = R.drawable.ht),
    CountryInfo("Heard Island and Mcdonald Islands", Country.HM, "+672", flag = R.drawable.hm),
    CountryInfo("Honduras", Country.HN, "+504", flag = R.drawable.hn),
    CountryInfo("Hong Kong", Country.HK, "+852", flag = R.drawable.hk),
    CountryInfo("Hungary", Country.HU, "+36", flag = R.drawable.hu),
    CountryInfo("Iceland", Country.IS, "+354", flag = R.drawable.`is`),
    CountryInfo("India", Country.IN, "+91", flag = R.drawable.`in`),
    CountryInfo("Indonesia", Country.ID, "+62", flag = R.drawable.id),
    CountryInfo("Iran", Country.IR, "+98", flag = R.drawable.ir),
    CountryInfo("Iraq", Country.IQ, "+964", flag = R.drawable.iq),
    CountryInfo("Ireland", Country.IE, "+353", flag = R.drawable.ie),
    CountryInfo("Isle of Man", Country.IM, "+44", flag = R.drawable.im),
    CountryInfo("Israel", Country.IL, "+972", flag = R.drawable.il),
    CountryInfo("Italy", Country.IT, "+39", flag = R.drawable.it),
    CountryInfo("Jamaica", Country.JM, "+1", flag = R.drawable.jm),
    CountryInfo("Japan", Country.JP, "+81", flag = R.drawable.jp),
    CountryInfo("Jersey", Country.JE, "+44", flag = R.drawable.je),
    CountryInfo("Jordan", Country.JO, "+962", flag = R.drawable.jo),
    CountryInfo("Kazakhstan", Country.KZ, "+7", flag = R.drawable.kz),
    CountryInfo("Kenya", Country.KE, "+254", flag = R.drawable.ke),
    CountryInfo("Kiribati", Country.KI, "+686", flag = R.drawable.ki),
    CountryInfo("Korea, Democratic People's Republic of", Country.KP, "+850", flag = R.drawable.kp, tags = listOf("North Korea", "DPRK")),
    CountryInfo("Korea, Republic of", Country.KR, "+82", flag = R.drawable.kr, tags = listOf("South Korea", "ROK")),
    CountryInfo("Kuwait", Country.KW, "+965", flag = R.drawable.kw),
    CountryInfo("Kyrgyzstan", Country.KG, "+996", flag = R.drawable.kg),
    CountryInfo("Lao People's Democratic Republic", Country.LA, "+856", flag = R.drawable.la, tags = listOf("Laos")),
    CountryInfo("Latvia", Country.LV, "+371", flag = R.drawable.lv),
    CountryInfo("Lebanon", Country.LB, "+961", flag = R.drawable.lb),
    CountryInfo("Lesotho", Country.LS, "+266", flag = R.drawable.ls),
    CountryInfo("Liberia", Country.LR, "+231", flag = R.drawable.lr),
    CountryInfo("Libyan Arab Jamahiriya", Country.LY, "+218", flag = R.drawable.ly, tags = listOf("Libya")),
    CountryInfo("Liechtenstein", Country.LI, "+423", flag = R.drawable.li),
    CountryInfo("Lithuania", Country.LT, "+370", flag = R.drawable.lt),
    CountryInfo("Luxembourg", Country.LU, "+352", flag = R.drawable.lu),
    CountryInfo("Macao", Country.MO, "+853", flag = R.drawable.mo),
    CountryInfo("Macedonia", Country.MK, "+389", flag = R.drawable.mk),
    CountryInfo("Madagascar", Country.MG, "+261", flag = R.drawable.mg),
    CountryInfo("Malawi", Country.MW, "+265", flag = R.drawable.mw),
    CountryInfo("Malaysia", Country.MY, "+60", flag = R.drawable.my),
    CountryInfo("Maldives", Country.MV, "+960", flag = R.drawable.mv),
    CountryInfo("Mali", Country.ML, "+223", flag = R.drawable.ml),
    CountryInfo("Malta", Country.MT, "+356", flag = R.drawable.mt),
    CountryInfo("Marshall Islands", Country.MH, "+692", flag = R.drawable.mh),
    CountryInfo("Martinique", Country.MQ, "+596", flag = R.drawable.mq),
    CountryInfo("Mauritania", Country.MR, "+222", flag = R.drawable.mr),
    CountryInfo("Mauritius", Country.MU, "+230", flag = R.drawable.mu),
    CountryInfo("Mayotte", Country.YT, "+262", flag = R.drawable.yt),
    CountryInfo("Mexico", Country.MX, "+52", flag = R.drawable.mx),
    CountryInfo("Micronesia", Country.FM, "+691", flag = R.drawable.fm),
    CountryInfo("Moldova", Country.MD, "+373", flag = R.drawable.md),
    CountryInfo("Monaco", Country.MC, "+377", flag = R.drawable.mc),
    CountryInfo("Mongolia", Country.MN, "+976", flag = R.drawable.mn),
    CountryInfo("Montenegro", Country.ME, "+382", flag = R.drawable.me),
    CountryInfo("Montserrat", Country.MS, "+1", flag = R.drawable.ms),
    CountryInfo("Morocco", Country.MA, "+212", flag = R.drawable.ma),
    CountryInfo("Mozambique", Country.MZ, "+258", flag = R.drawable.mz),
    CountryInfo("Myanmar", Country.MM, "+95", flag = R.drawable.mm),
    CountryInfo("Namibia", Country.NA, "+264", flag = R.drawable.na),
    CountryInfo("Nauru", Country.NR, "+674", flag = R.drawable.nr),
    CountryInfo("Nepal", Country.NP, "+977", flag = R.drawable.np),
    CountryInfo("Netherlands", Country.NL, "+31", flag = R.drawable.nl, tags = listOf("Holland")),
    CountryInfo("Netherlands Antilles", Country.AN, "+599", flag = R.drawable.an, tags = listOf("Curacao", "Bonaire", "Saba", "Sint Maarten", "Sint Eustatius")),
    CountryInfo("New Caledonia", Country.NC, "+687", flag = R.drawable.nc),
    CountryInfo("New Zealand", Country.NZ, "+64", flag = R.drawable.nz),
    CountryInfo("Nicaragua", Country.NI, "+505", flag = R.drawable.ni),
    CountryInfo("Niger", Country.NE, "+227", flag = R.drawable.ne),
    CountryInfo("Nigeria", Country.NG, "+234", flag = R.drawable.ng),
    CountryInfo("Niue", Country.NU, "+683", flag = R.drawable.nu),
    CountryInfo("Norfolk Island", Country.NF, "+672", flag = R.drawable.nf),
    CountryInfo("Northern Mariana Islands", Country.MP, "+1", flag = R.drawable.mp),
    CountryInfo("Norway", Country.NO, "+47", flag = R.drawable.no),
    CountryInfo("Oman", Country.OM, "+968", flag = R.drawable.om),
    CountryInfo("Pakistan", Country.PK, "+92", flag = R.drawable.pk),
    CountryInfo("Palau", Country.PW, "+680", flag = R.drawable.pw),
    CountryInfo("Palestine", Country.PS, "+970", flag = R.drawable.ps),
    CountryInfo("Panama", Country.PA, "+507", flag = R.drawable.pa),
    CountryInfo("Papua New Guinea", Country.PG, "+675", flag = R.drawable.pg),
    CountryInfo("Paraguay", Country.PY, "+595", flag = R.drawable.py),
    CountryInfo("Peru", Country.PE, "+51", flag = R.drawable.pe),
    CountryInfo("Philippines", Country.PH, "+63", flag = R.drawable.ph),
    CountryInfo("Pitcairn", Country.PN, "+870", flag = R.drawable.pn),
    CountryInfo("Poland", Country.PL, "+48", flag = R.drawable.pl),
    CountryInfo("Portugal", Country.PT, "+351", flag = R.drawable.pt),
    CountryInfo("Puerto Rico", Country.PR, "+1", flag = R.drawable.pr),
    CountryInfo("Qatar", Country.QA, "+974", flag = R.drawable.qa),
    CountryInfo("Reunion", Country.RE, "+262", flag = R.drawable.re),
    CountryInfo("Romania", Country.RO, "+40", flag = R.drawable.ro),
    CountryInfo("Russian Federation", Country.RU, "+7", flag = R.drawable.ru),
    CountryInfo("Rwanda", Country.RW, "+250", flag = R.drawable.rw, tags = listOf("Kigali")),
    CountryInfo("Saint Helena", Country.SH, "+290", flag = R.drawable.sh),
    CountryInfo("Saint Kitts and Nevis", Country.KN, "+1", flag = R.drawable.kn),
    CountryInfo("Saint Lucia", Country.LC, "+1", flag = R.drawable.lc),
    CountryInfo("Saint Pierre and Miquelon", Country.PM, "+508", flag = R.drawable.pm, tags = listOf("St. Pierre and Miquelon")),
    CountryInfo("Saint Vincent and the Grenadines", Country.VC, "+1", flag = R.drawable.vc, tags = listOf("St. Vincent and the Grenadines")),
    CountryInfo("Samoa", Country.WS, "+685", flag = R.drawable.ws),
    CountryInfo("San Marino", Country.SM, "+378", flag = R.drawable.sm),
    CountryInfo("Sao Tome and Principe", Country.ST, "+239", flag = R.drawable.st, tags = listOf("São Tomé and Príncipe")),
    CountryInfo("Saudi Arabia", Country.SA, "+966", flag = R.drawable.sa, tags = listOf("KSA", "Kingdom of Saudi Arabia")),
    CountryInfo("Senegal", Country.SN, "+221", flag = R.drawable.sn),
    CountryInfo("Serbia", Country.RS, "+381", flag = R.drawable.rs),
    CountryInfo("Seychelles", Country.SC, "+248", flag = R.drawable.sc),
    CountryInfo("Sierra Leone", Country.SL, "+232", flag = R.drawable.sl),
    CountryInfo("Singapore", Country.SG, "+65", flag = R.drawable.sg),
    CountryInfo("Slovakia", Country.SK, "+421", flag = R.drawable.sk),
    CountryInfo("Slovenia", Country.SI, "+386", flag = R.drawable.si),
    CountryInfo("Solomon Islands", Country.SB, "+677", flag = R.drawable.sb),
    CountryInfo("Somalia", Country.SO, "+252", flag = R.drawable.so),
    CountryInfo("South Africa", Country.ZA, "+27", flag = R.drawable.za),
    CountryInfo("South Sudan", Country.SS, "+211", flag = R.drawable.ss),
    CountryInfo("Spain", Country.ES, "+34", flag = R.drawable.es),
    CountryInfo("Sri Lanka", Country.LK, "+94", flag = R.drawable.lk, tags = listOf("Ceylon")),
    CountryInfo("Sudan", Country.SD, "+249", flag = R.drawable.sd),
    CountryInfo("Suriname", Country.SR, "+597", flag = R.drawable.sr),
    CountryInfo("Sweden", Country.SE, "+46", flag = R.drawable.se, tags = listOf("Sverige")),
    CountryInfo("Switzerland", Country.CH, "+41", flag = R.drawable.ch, tags = listOf("Swiss Confederation")),
    CountryInfo("Syria", Country.SY, "+963", flag = R.drawable.sy),
    CountryInfo("Taiwan", Country.TW, "+886", flag = R.drawable.tw),
    CountryInfo("Tajikistan", Country.TJ, "+992", flag = R.drawable.tj),
    CountryInfo("Tanzania, United Republic of", Country.TZ, "+255", flag = R.drawable.tz, tags = listOf("Zanzibar", "Tanganyika")),
    CountryInfo("Thailand", Country.TH, "+66", flag = R.drawable.th),
    CountryInfo("Timor-Leste", Country.TL, "+670", flag = R.drawable.tl),
    CountryInfo("Togo", Country.TG, "+228", flag = R.drawable.tg),
    CountryInfo("Tokelau", Country.TK, "+690", flag = R.drawable.tk),
    CountryInfo("Tonga", Country.TO, "+676", flag = R.drawable.to),
    CountryInfo("Trinidad and Tobago", Country.TT, "+1", flag = R.drawable.tt),
    CountryInfo("Tunisia", Country.TN, "+216", flag = R.drawable.tn),
    CountryInfo("Turkey", Country.TR, "+90", flag = R.drawable.tr),
    CountryInfo("Turkmenistan", Country.TM, "+993", flag = R.drawable.tm),
    CountryInfo("Turks and Caicos Islands", Country.TC, "+1", flag = R.drawable.tc),
    CountryInfo("Tuvalu", Country.TV, "+688", flag = R.drawable.tv),
    CountryInfo("Uganda", Country.UG, "+256", flag = R.drawable.ug),
    CountryInfo("Ukraine", Country.UA, "+380", flag = R.drawable.ua),
    CountryInfo("United Arab Emirates", Country.AE, "+971", flag = R.drawable.ae, tags = listOf("UAE", "Emirates", "Dubai", "Abu Dhabi")),
    CountryInfo("United Kingdom", Country.GB, "+44", flag = R.drawable.gb, tags = listOf("UK", "GB")),
    CountryInfo("United States", Country.US, "+1", flag = R.drawable.us, tags = listOf("USA", "US", "America")),
    CountryInfo("Uruguay", Country.UY, "+598", flag = R.drawable.uy),
    CountryInfo("Uzbekistan", Country.UZ, "+998", flag = R.drawable.uz),
    CountryInfo("Vanuatu", Country.VU, "+678", flag = R.drawable.vu),
    CountryInfo("Vatican", Country.VA, "+379", flag = R.drawable.va),
    CountryInfo("Venezuela", Country.VE, "+58", flag = R.drawable.ve),
    CountryInfo("Vietnam", Country.VN, "+84", flag = R.drawable.vn),
    CountryInfo("Virgin Islands, British", Country.VG, "+1", flag = R.drawable.vg),
    CountryInfo("Virgin Islands, U.S.", Country.VI, "+1", flag = R.drawable.vi),
    CountryInfo("Wallis and Futuna", Country.WF, "+681", flag = R.drawable.wf),
    CountryInfo("Western Sahara", Country.EH, "+212", flag = R.drawable.eh),
    CountryInfo("Yemen", Country.YE, "+967", flag = R.drawable.ye),
    CountryInfo("Zambia", Country.ZM, "+260", flag = R.drawable.zm),
    CountryInfo("Zimbabwe", Country.ZW, "+263", flag = R.drawable.zw)
)

enum class Country {
    AF,
    AX,
    AL,
    DZ,
    AS,
    AD,
    AO,
    AI,
    AQ,
    AG,
    AR,
    AM,
    AW,
    AU,
    AT,
    AZ,
    BS,
    BH,
    BD,
    BB,
    BY,
    BE,
    BZ,
    BJ,
    BM,
    BT,
    BO,
    BA,
    BW,
    BV,
    BR,
    IO,
    BN,
    BG,
    BF,
    BI,
    KH,
    CM,
    CA,
    CV,
    KY,
    CF,
    TD,
    CL,
    CN,
    CX,
    CC,
    CO,
    KM,
    CG,
    CD,
    CK,
    CR,
    HR,
    CU,
    CY,
    CZ,
    DK,
    DJ,
    DM,
    DO,
    EC,
    EG,
    SV,
    GQ,
    ER,
    EE,
    SZ,
    ET,
    FK,
    FO,
    FJ,
    FI,
    FR,
    GF,
    PF,
    TF,
    GA,
    GM,
    GE,
    DE,
    GH,
    GI,
    GR,
    GL,
    GD,
    GP,
    GU,
    GT,
    GG,
    GN,
    GW,
    GY,
    HT,
    HM,
    HN,
    HK,
    HU,
    IS,
    IN,
    ID,
    IR,
    IQ,
    IE,
    IM,
    IL,
    IT,
    JM,
    JP,
    JE,
    JO,
    KZ,
    KE,
    KI,
    KP,
    KR,
    KW,
    KG,
    LA,
    LV,
    LB,
    LS,
    LR,
    LY,
    LI,
    LT,
    LU,
    MO,
    MK,
    MG,
    MW,
    MY,
    MV,
    ML,
    MT,
    MH,
    MQ,
    MR,
    MU,
    YT,
    MX,
    FM,
    MD,
    MC,
    MN,
    ME,
    MS,
    MA,
    MZ,
    MM,
    NA,
    NR,
    NP,
    NL,
    AN,
    NC,
    NZ,
    NI,
    NE,
    NG,
    NU,
    NF,
    MP,
    NO,
    OM,
    PK,
    PW,
    PS,
    PA,
    PG,
    PY,
    PE,
    PH,
    PN,
    PL,
    PT,
    PR,
    QA,
    RE,
    RO,
    RU,
    RW,
    SH,
    KN,
    LC,
    PM,
    VC,
    WS,
    SM,
    ST,
    SA,
    SN,
    RS,
    SC,
    SL,
    SG,
    SK,
    SI,
    SB,
    SO,
    ZA,
    ES,
    LK,
    SD,
    SR,
    SS,
    SE,
    CH,
    SY,
    TW,
    TJ,
    TZ,
    TH,
    TL,
    TG,
    TK,
    TO,
    TT,
    TN,
    TR,
    TM,
    TC,
    TV,
    UG,
    UA,
    AE,
    GB,
    US,
    UY,
    UZ,
    VU,
    VA,
    VE,
    VN,
    VG,
    VI,
    WF,
    EH,
    YE,
    ZM,
    ZW
}

/**
 * Allows you to filter the list of countries by including only the countries you want
 * Note that includeOnly takes precedence over omit
 * @param includeOnly a list of country codes to include. Country codes must be in ISO 3166-1 alpha-2 format. ex: ["RW", "KE"]
 * @param omit a list of country codes to omit Country codes must be  in ISO 3166-1 alpha-2 format
 * */
fun resolveCountries(
    includeOnly: List<Country> = listOf(),
    omit: List<Country> = listOf(),
): List<CountryInfo> {
    if(includeOnly.isNotEmpty()) return countryList.filter { country -> includeOnly.contains(country.code) }
    if(omit.isNotEmpty()) countryList.filter { country -> !omit.contains(country.code) }
    return countryList
}

/*
* name = country name
* code = country code
* dialingCode = country dialing code
* flag = country flag
* for example, Dominican Republic has a country code of DO but the drawable code is DO_O because DO is a reserved keyword
* */
data class CountryInfo(val name: String, val code: Country, val dialingCode: String, @DrawableRes val flag: Int, val tags: List<String> = listOf())
