stages:
  - publish

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG  # Only run when a tag is created

  image: gradle:jdk17
  variables:
    PROJECT_ID: $CI_PROJECT_ID
    ANDROID_HOME: /android-sdk
  
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends wget unzip libstdc++6
    - wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
    - unzip commandlinetools-linux-11076708_latest.zip
    - mkdir -p $ANDROID_HOME/cmdline-tools
    - mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
    - chmod +x $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
    - yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
    - yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-34" "build-tools;34.0.0" || true
    - export GRADLE_USER_HOME=$PWD/.gradle

  script:
    - chmod +x ./gradlew
    - ./gradlew publish -Pversion=$CI_COMMIT_TAG  # Publish with tag as version

