package com.isakaro.qwik.utils

import androidx.annotation.DrawableRes
import com.isakaro.qwik.R

val countryList = listOf(
    CountryInfo("Afghanistan", "AF", "+93", flag = R.drawable.af),
    CountryInfo("Åland Islands", "AX", "+358", flag = R.drawable.ax),
    CountryInfo("Albania", "AL", "+355", flag = R.drawable.al),
    CountryInfo("Algeria", "DZ", "+213", flag = R.drawable.dz),
    CountryInfo("American Samoa", "AS", "+1", flag = R.drawable.`as`),
    CountryInfo("Andorra", "AD", "+376", flag = R.drawable.ad),
    CountryInfo("Angola", "AO", "+244", flag = R.drawable.ao),
    CountryInfo("Anguilla", "AI", "+1", flag = R.drawable.ai),
    CountryInfo("Antarctica", "AQ", "+672", flag = R.drawable.aq),
    CountryInfo("Antigua and Barbuda", "AG", "+1", flag = R.drawable.ag),
    CountryInfo("Argentina", "AR", "+54", flag = R.drawable.ar),
    CountryInfo("Armenia", "AM", "+374", flag = R.drawable.am),
    CountryInfo("Aruba", "AW", "+297", flag = R.drawable.aw),
    CountryInfo("Australia", "AU", "+61", flag = R.drawable.au),
    CountryInfo("Austria", "AT", "+43", flag = R.drawable.at),
    CountryInfo("Azerbaijan", "AZ", "+994", flag = R.drawable.az),
    CountryInfo("Bahamas", "BS", "+1", flag = R.drawable.bs),
    CountryInfo("Bahrain", "BH", "+973", flag = R.drawable.bh),
    CountryInfo("Bangladesh", "BD", "+880", flag = R.drawable.bd),
    CountryInfo("Barbados", "BB", "+1", flag = R.drawable.bb),
    CountryInfo("Belarus", "BY", "+375", flag = R.drawable.by),
    CountryInfo("Belgium", "BE", "+32", flag = R.drawable.be),
    CountryInfo("Belize", "BZ", "+501", flag = R.drawable.bz),
    CountryInfo("Benin", "BJ", "+229", flag = R.drawable.bj),
    CountryInfo("Bermuda", "BM", "+1", flag = R.drawable.bm),
    CountryInfo("Bhutan", "BT", "+975", flag = R.drawable.bt),
    CountryInfo("Bolivia", "BO", "+591", flag = R.drawable.bo),
    CountryInfo("Bosnia and Herzegovina", "BA", "+387", flag = R.drawable.ba),
    CountryInfo("Botswana", "BW", "+267", flag = R.drawable.bw),
    CountryInfo("Bouvet Island", "BV", "+47", flag = R.drawable.bv),
    CountryInfo("Brazil", "BR", "+55", flag = R.drawable.br),
    CountryInfo("British Indian Ocean Territory", "IO", "+246", flag = R.drawable.io, tags = listOf("Chagos Islands")),
    CountryInfo("Brunei", "BN", "+673", flag = R.drawable.bn),
    CountryInfo("Bulgaria", "BG", "+359", flag = R.drawable.bg),
    CountryInfo("Burkina Faso", "BF", "+226", flag = R.drawable.bf),
    CountryInfo("Burundi", "BI", "+257", flag = R.drawable.bi),
    CountryInfo("Cambodia", "KH", "+855", flag = R.drawable.kh),
    CountryInfo("Cameroon", "CM", "+237", flag = R.drawable.cm),
    CountryInfo("Canada", "CA", "+1", flag = R.drawable.ca),
    CountryInfo("Cape Verde", "CV", "+238", flag = R.drawable.cv),
    CountryInfo("Cayman Islands", "KY", "+1", flag = R.drawable.ky),
    CountryInfo("Central African Republic", "CF", "+236", flag = R.drawable.cf, tags = listOf("CAR")),
    CountryInfo("Chad", "TD", "+235", flag = R.drawable.td),
    CountryInfo("Chile", "CL", "+56", flag = R.drawable.cl),
    CountryInfo("China", "CN", "+86", flag = R.drawable.cn),
    CountryInfo("Christmas Island", "CX", "+61", flag = R.drawable.cx),
    CountryInfo("Cocos (Keeling) Islands", "CC", "+61", flag = R.drawable.cc),
    CountryInfo("Colombia", "CO", "+57", flag = R.drawable.co),
    CountryInfo("Comoros", "KM", "+269", flag = R.drawable.km),
    CountryInfo("Congo, The Republic of the", "CG", "+242", flag = R.drawable.cg, tags = listOf("Brazzaville")),
    CountryInfo("Congo, The Democratic Republic of the", "CD", "+243", flag = R.drawable.cd, tags = listOf("DRC", "Kinshasa")),
    CountryInfo("Cook Islands", "CK", "+682", flag = R.drawable.ck),
    CountryInfo("Costa Rica", "CR", "+506", flag = R.drawable.cr),
    CountryInfo("Croatia", "HR", "+385", flag = R.drawable.hr),
    CountryInfo("Cuba", "CU", "+53", flag = R.drawable.cu),
    CountryInfo("Cyprus", "CY", "+357", flag = R.drawable.cy),
    CountryInfo("Czech Republic", "CZ", "+420", flag = R.drawable.cz),
    CountryInfo("Denmark", "DK", "+45", flag = R.drawable.dk),
    CountryInfo("Djibouti", "DJ", "+253", flag = R.drawable.dj),
    CountryInfo("Dominica", "DM", "+1", flag = R.drawable.dm),
    CountryInfo("Dominican Republic", "DO_O", "+1", flag = R.drawable.do_),
    CountryInfo("Ecuador", "EC", "+593", flag = R.drawable.ec),
    CountryInfo("Egypt", "EG", "+20", flag = R.drawable.eg),
    CountryInfo("El Salvador", "SV", "+503", flag = R.drawable.sv),
    CountryInfo("Equatorial Guinea", "GQ", "+240", flag = R.drawable.gq),
    CountryInfo("Eritrea", "ER", "+291", flag = R.drawable.er),
    CountryInfo("Estonia", "EE", "+372", flag = R.drawable.ee),
    CountryInfo("eSwatini", "SZ", "+268", flag = R.drawable.sz),
    CountryInfo("Ethiopia", "ET", "+251", flag = R.drawable.et),
    CountryInfo("Falkland Islands (Malvinas)", "FK", "+500", flag = R.drawable.fk),
    CountryInfo("Faroe Islands", "FO", "+298", flag = R.drawable.fo),
    CountryInfo("Fiji", "FJ", "+679", flag = R.drawable.fj),
    CountryInfo("Finland", "FI", "+358", flag = R.drawable.fi),
    CountryInfo("France", "FR", "+33", flag = R.drawable.fr),
    CountryInfo("French Guiana", "GF", "+594", flag = R.drawable.gf),
    CountryInfo("French Polynesia", "PF", "+689", flag = R.drawable.pf),
    CountryInfo("French Southern Territories", "TF", "+262", flag = R.drawable.tf),
    CountryInfo("Gabon", "GA", "+241", flag = R.drawable.ga),
    CountryInfo("Gambia", "GM", "+220", flag = R.drawable.gm),
    CountryInfo("Georgia", "GE", "+995", flag = R.drawable.ge),
    CountryInfo("Germany", "DE", "+49", flag = R.drawable.de, tags = listOf("Deutschland", "Federal Republic of Germany")),
    CountryInfo("Ghana", "GH", "+233", flag = R.drawable.gh),
    CountryInfo("Gibraltar", "GI", "+350", flag = R.drawable.gi),
    CountryInfo("Greece", "GR", "+30", flag = R.drawable.gr),
    CountryInfo("Greenland", "GL", "+299", flag = R.drawable.gl),
    CountryInfo("Grenada", "GD", "+1", flag = R.drawable.gd),
    CountryInfo("Guadeloupe", "GP", "+590", flag = R.drawable.gp),
    CountryInfo("Guam", "GU", "+1", flag = R.drawable.gu),
    CountryInfo("Guatemala", "GT", "+502", flag = R.drawable.gt),
    CountryInfo("Guernsey", "GG", "+44", flag = R.drawable.gg),
    CountryInfo("Guinea", "GN", "+224", flag = R.drawable.gn),
    CountryInfo("Guinea-Bissau", "GW", "+245", flag = R.drawable.gw),
    CountryInfo("Guyana", "GY", "+592", flag = R.drawable.gy),
    CountryInfo("Haiti", "HT", "+509", flag = R.drawable.ht),
    CountryInfo("Heard Island and Mcdonald Islands", "HM", "+672", flag = R.drawable.hm),
    CountryInfo("Honduras", "HN", "+504", flag = R.drawable.hn),
    CountryInfo("Hong Kong", "HK", "+852", flag = R.drawable.hk),
    CountryInfo("Hungary", "HU", "+36", flag = R.drawable.hu),
    CountryInfo("Iceland", "IS", "+354", flag = R.drawable.`is`),
    CountryInfo("India", "IN", "+91", flag = R.drawable.`in`),
    CountryInfo("Indonesia", "ID", "+62", flag = R.drawable.id),
    CountryInfo("Iran", "IR", "+98", flag = R.drawable.ir),
    CountryInfo("Iraq", "IQ", "+964", flag = R.drawable.iq),
    CountryInfo("Ireland", "IE", "+353", flag = R.drawable.ie),
    CountryInfo("Isle of Man", "IM", "+44", flag = R.drawable.im),
    CountryInfo("Israel", "IL", "+972", flag = R.drawable.il),
    CountryInfo("Italy", "IT", "+39", flag = R.drawable.it),
    CountryInfo("Jamaica", "JM", "+1", flag = R.drawable.jm),
    CountryInfo("Japan", "JP", "+81", flag = R.drawable.jp),
    CountryInfo("Jersey", "JE", "+44", flag = R.drawable.je),
    CountryInfo("Jordan", "JO", "+962", flag = R.drawable.jo),
    CountryInfo("Kazakhstan", "KZ", "+7", flag = R.drawable.kz),
    CountryInfo("Kenya", "KE", "+254", flag = R.drawable.ke),
    CountryInfo("Kiribati", "KI", "+686", flag = R.drawable.ki),
    CountryInfo("Korea, Democratic People's Republic of", "KP", "+850", flag = R.drawable.kp, tags = listOf("North Korea", "DPRK")),
    CountryInfo("Korea, Republic of", "KR", "+82", flag = R.drawable.kr, tags = listOf("South Korea", "ROK")),
    CountryInfo("Kuwait", "KW", "+965", flag = R.drawable.kw),
    CountryInfo("Kyrgyzstan", "KG", "+996", flag = R.drawable.kg),
    CountryInfo("Lao People's Democratic Republic", "LA", "+856", flag = R.drawable.la, tags = listOf("Laos")),
    CountryInfo("Latvia", "LV", "+371", flag = R.drawable.lv),
    CountryInfo("Lebanon", "LB", "+961", flag = R.drawable.lb),
    CountryInfo("Lesotho", "LS", "+266", flag = R.drawable.ls),
    CountryInfo("Liberia", "LR", "+231", flag = R.drawable.lr),
    CountryInfo("Libyan Arab Jamahiriya", "LY", "+218", flag = R.drawable.ly, tags = listOf("Libya")),
    CountryInfo("Liechtenstein", "LI", "+423", flag = R.drawable.li),
    CountryInfo("Lithuania", "LT", "+370", flag = R.drawable.lt),
    CountryInfo("Luxembourg", "LU", "+352", flag = R.drawable.lu),
    CountryInfo("Macao", "MO", "+853", flag = R.drawable.mo),
    CountryInfo("Macedonia", "MK", "+389", flag = R.drawable.mk),
    CountryInfo("Madagascar", "MG", "+261", flag = R.drawable.mg),
    CountryInfo("Malawi", "MW", "+265", flag = R.drawable.mw),
    CountryInfo("Malaysia", "MY", "+60", flag = R.drawable.my),
    CountryInfo("Maldives", "MV", "+960", flag = R.drawable.mv),
    CountryInfo("Mali", "ML", "+223", flag = R.drawable.ml),
    CountryInfo("Malta", "MT", "+356", flag = R.drawable.mt),
    CountryInfo("Marshall Islands", "MH", "+692", flag = R.drawable.mh),
    CountryInfo("Martinique", "MQ", "+596", flag = R.drawable.mq),
    CountryInfo("Mauritania", "MR", "+222", flag = R.drawable.mr),
    CountryInfo("Mauritius", "MU", "+230", flag = R.drawable.mu),
    CountryInfo("Mayotte", "YT", "+262", flag = R.drawable.yt),
    CountryInfo("Mexico", "MX", "+52", flag = R.drawable.mx),
    CountryInfo("Micronesia", "FM", "+691", flag = R.drawable.fm),
    CountryInfo("Moldova", "MD", "+373", flag = R.drawable.md),
    CountryInfo("Monaco", "MC", "+377", flag = R.drawable.mc),
    CountryInfo("Mongolia", "MN", "+976", flag = R.drawable.mn),
    CountryInfo("Montenegro", "ME", "+382", flag = R.drawable.me),
    CountryInfo("Montserrat", "MS", "+1", flag = R.drawable.ms),
    CountryInfo("Morocco", "MA", "+212", flag = R.drawable.ma),
    CountryInfo("Mozambique", "MZ", "+258", flag = R.drawable.mz),
    CountryInfo("Myanmar", "MM", "+95", flag = R.drawable.mm),
    CountryInfo("Namibia", "NA", "+264", flag = R.drawable.na),
    CountryInfo("Nauru", "NR", "+674", flag = R.drawable.nr),
    CountryInfo("Nepal", "NP", "+977", flag = R.drawable.np),
    CountryInfo("Netherlands", "NL", "+31", flag = R.drawable.nl, tags = listOf("Holland")),
    CountryInfo("Netherlands Antilles", "AN", "+599", flag = R.drawable.an, tags = listOf("Curacao", "Bonaire", "Saba", "Sint Maarten", "Sint Eustatius")),
    CountryInfo("New Caledonia", "NC", "+687", flag = R.drawable.nc),
    CountryInfo("New Zealand", "NZ", "+64", flag = R.drawable.nz),
    CountryInfo("Nicaragua", "NI", "+505", flag = R.drawable.ni),
    CountryInfo("Niger", "NE", "+227", flag = R.drawable.ne),
    CountryInfo("Nigeria", "NG", "+234", flag = R.drawable.ng),
    CountryInfo("Niue", "NU", "+683", flag = R.drawable.nu),
    CountryInfo("Norfolk Island", "NF", "+672", flag = R.drawable.nf),
    CountryInfo("Northern Mariana Islands", "MP", "+1", flag = R.drawable.mp),
    CountryInfo("Norway", "NO", "+47", flag = R.drawable.no),
    CountryInfo("Oman", "OM", "+968", flag = R.drawable.om),
    CountryInfo("Pakistan", "PK", "+92", flag = R.drawable.pk),
    CountryInfo("Palau", "PW", "+680", flag = R.drawable.pw),
    CountryInfo("Palestine", "PS", "+970", flag = R.drawable.ps),
    CountryInfo("Panama", "PA", "+507", flag = R.drawable.pa),
    CountryInfo("Papua New Guinea", "PG", "+675", flag = R.drawable.pg),
    CountryInfo("Paraguay", "PY", "+595", flag = R.drawable.py),
    CountryInfo("Peru", "PE", "+51", flag = R.drawable.pe),
    CountryInfo("Philippines", "PH", "+63", flag = R.drawable.ph),
    CountryInfo("Pitcairn", "PN", "+870", flag = R.drawable.pn),
    CountryInfo("Poland", "PL", "+48", flag = R.drawable.pl),
    CountryInfo("Portugal", "PT", "+351", flag = R.drawable.pt),
    CountryInfo("Puerto Rico", "PR", "+1", flag = R.drawable.pr),
    CountryInfo("Qatar", "QA", "+974", flag = R.drawable.qa),
    CountryInfo("Reunion", "RE", "+262", flag = R.drawable.re),
    CountryInfo("Romania", "RO", "+40", flag = R.drawable.ro),
    CountryInfo("Russian Federation", "RU", "+7", flag = R.drawable.ru),
    CountryInfo("Rwanda", "RW", "+250", flag = R.drawable.rw, tags = listOf("Kigali")),
    CountryInfo("Saint Helena", "SH", "+290", flag = R.drawable.sh),
    CountryInfo("Saint Kitts and Nevis", "KN", "+1", flag = R.drawable.kn),
    CountryInfo("Saint Lucia", "LC", "+1", flag = R.drawable.lc),
    CountryInfo("Saint Pierre and Miquelon", "PM", "+508", flag = R.drawable.pm, tags = listOf("St. Pierre and Miquelon")),
    CountryInfo("Saint Vincent and the Grenadines", "VC", "+1", flag = R.drawable.vc, tags = listOf("St. Vincent and the Grenadines")),
    CountryInfo("Samoa", "WS", "+685", flag = R.drawable.ws),
    CountryInfo("San Marino", "SM", "+378", flag = R.drawable.sm),
    CountryInfo("Sao Tome and Principe", "ST", "+239", flag = R.drawable.st, tags = listOf("São Tomé and Príncipe")),
    CountryInfo("Saudi Arabia", "SA", "+966", flag = R.drawable.sa, tags = listOf("KSA", "Kingdom of Saudi Arabia")),
    CountryInfo("Senegal", "SN", "+221", flag = R.drawable.sn),
    CountryInfo("Serbia", "RS", "+381", flag = R.drawable.rs),
    CountryInfo("Seychelles", "SC", "+248", flag = R.drawable.sc),
    CountryInfo("Sierra Leone", "SL", "+232", flag = R.drawable.sl),
    CountryInfo("Singapore", "SG", "+65", flag = R.drawable.sg),
    CountryInfo("Slovakia", "SK", "+421", flag = R.drawable.sk),
    CountryInfo("Slovenia", "SI", "+386", flag = R.drawable.si),
    CountryInfo("Solomon Islands", "SB", "+677", flag = R.drawable.sb),
    CountryInfo("Somalia", "SO", "+252", flag = R.drawable.so),
    CountryInfo("South Africa", "ZA", "+27", flag = R.drawable.za),
    CountryInfo("South Sudan", "SS", "+211", flag = R.drawable.ss),
    CountryInfo("Spain", "ES", "+34", flag = R.drawable.es),
    CountryInfo("Sri Lanka", "LK", "+94", flag = R.drawable.lk, tags = listOf("Ceylon")),
    CountryInfo("Sudan", "SD", "+249", flag = R.drawable.sd),
    CountryInfo("Suriname", "SR", "+597", flag = R.drawable.sr),
    CountryInfo("Sweden", "SE", "+46", flag = R.drawable.se, tags = listOf("Sverige")),
    CountryInfo("Switzerland", "CH", "+41", flag = R.drawable.ch, tags = listOf("Swiss Confederation")),
    CountryInfo("Syria", "SY", "+963", flag = R.drawable.sy),
    CountryInfo("Taiwan", "TW", "+886", flag = R.drawable.tw),
    CountryInfo("Tajikistan", "TJ", "+992", flag = R.drawable.tj),
    CountryInfo("Tanzania, United Republic of", "TZ", "+255", flag = R.drawable.tz, tags = listOf("Zanzibar", "Tanganyika")),
    CountryInfo("Thailand", "TH", "+66", flag = R.drawable.th),
    CountryInfo("Timor-Leste", "TL", "+670", flag = R.drawable.tl),
    CountryInfo("Togo", "TG", "+228", flag = R.drawable.tg),
    CountryInfo("Tokelau", "TK", "+690", flag = R.drawable.tk),
    CountryInfo("Tonga", "TO", "+676", flag = R.drawable.to),
    CountryInfo("Trinidad and Tobago", "TT", "+1", flag = R.drawable.tt),
    CountryInfo("Tunisia", "TN", "+216", flag = R.drawable.tn),
    CountryInfo("Turkey", "TR", "+90", flag = R.drawable.tr),
    CountryInfo("Turkmenistan", "TM", "+993", flag = R.drawable.tm),
    CountryInfo("Turks and Caicos Islands", "TC", "+1", flag = R.drawable.tc),
    CountryInfo("Tuvalu", "TV", "+688", flag = R.drawable.tv),
    CountryInfo("Uganda", "UG", "+256", flag = R.drawable.ug),
    CountryInfo("Ukraine", "UA", "+380", flag = R.drawable.ua),
    CountryInfo("United Arab Emirates", "AE", "+971", flag = R.drawable.ae, tags = listOf("UAE", "Emirates", "Dubai", "Abu Dhabi")),
    CountryInfo("United Kingdom", "GB", "+44", flag = R.drawable.gb, tags = listOf("UK", "GB")),
    CountryInfo("United States", "US", "+1", flag = R.drawable.us, tags = listOf("USA", "US", "America")),
    CountryInfo("Uruguay", "UY", "+598", flag = R.drawable.uy),
    CountryInfo("Uzbekistan", "UZ", "+998", flag = R.drawable.uz),
    CountryInfo("Vanuatu", "VU", "+678", flag = R.drawable.vu),
    CountryInfo("Vatican", "VA", "+379", flag = R.drawable.va),
    CountryInfo("Venezuela", "VE", "+58", flag = R.drawable.ve),
    CountryInfo("Vietnam", "VN", "+84", flag = R.drawable.vn),
    CountryInfo("Virgin Islands, British", "VG", "+1", flag = R.drawable.vg),
    CountryInfo("Virgin Islands, U.S.", "VI", "+1", flag = R.drawable.vi),
    CountryInfo("Wallis and Futuna", "WF", "+681", flag = R.drawable.wf),
    CountryInfo("Western Sahara", "EH", "+212", flag = R.drawable.eh),
    CountryInfo("Yemen", "YE", "+967", flag = R.drawable.ye),
    CountryInfo("Zambia", "ZM", "+260", flag = R.drawable.zm),
    CountryInfo("Zimbabwe", "ZW", "+263", flag = R.drawable.zw)
)

fun resolveCountries(omit: List<String> = listOf()): List<CountryInfo> {
    if(omit.isEmpty()) return countryList
    return countryList.filter { country -> !omit.contains(country.code) }
}

/*
* name = country name
* code = country code
* dialingCode = country dialing code
* flag = country flag
* for example, Dominican Republic has a country code of DO but the drawable code is DO_O because DO is a reserved keyword
* */
data class CountryInfo(val name: String, val code: String, val dialingCode: String, @DrawableRes val flag: Int, val tags: List<String> = listOf())
