package com.isakaro.kwik.ui.utils

import android.content.Context
import android.content.Context.TELEPHONY_SERVICE
import android.telephony.TelephonyManager
import androidx.annotation.DrawableRes
import com.isakaro.R
import java.util.Locale

val countryList = listOf(
    KwikCountryInfo("Afghanistan", KwikCountry.AF, "+93", flag = R.drawable.af),
    KwikCountryInfo("Åland Islands", KwikCountry.AX, "+358", flag = R.drawable.ax),
    KwikCountryInfo("Albania", KwikCountry.AL, "+355", flag = R.drawable.al),
    KwikCountryInfo("Algeria", KwikCountry.DZ, "+213", flag = R.drawable.dz),
    KwikCountryInfo("American Samoa", KwikCountry.AS, "+1", flag = R.drawable.`as`),
    KwikCountryInfo("Andorra", KwikCountry.AD, "+376", flag = R.drawable.ad),
    KwikCountryInfo("Angola", KwikCountry.AO, "+244", flag = R.drawable.ao),
    KwikCountryInfo("Anguilla", KwikCountry.AI, "+1", flag = R.drawable.ai),
    KwikCountryInfo("Antarctica", KwikCountry.AQ, "+672", flag = R.drawable.aq),
    KwikCountryInfo("Antigua and Barbuda", KwikCountry.AG, "+1", flag = R.drawable.ag),
    KwikCountryInfo("Argentina", KwikCountry.AR, "+54", flag = R.drawable.ar),
    KwikCountryInfo("Armenia", KwikCountry.AM, "+374", flag = R.drawable.am),
    KwikCountryInfo("Aruba", KwikCountry.AW, "+297", flag = R.drawable.aw),
    KwikCountryInfo("Australia", KwikCountry.AU, "+61", flag = R.drawable.au),
    KwikCountryInfo("Austria", KwikCountry.AT, "+43", flag = R.drawable.at),
    KwikCountryInfo("Azerbaijan", KwikCountry.AZ, "+994", flag = R.drawable.az),
    KwikCountryInfo("Bahamas", KwikCountry.BS, "+1", flag = R.drawable.bs),
    KwikCountryInfo("Bahrain", KwikCountry.BH, "+973", flag = R.drawable.bh),
    KwikCountryInfo("Bangladesh", KwikCountry.BD, "+880", flag = R.drawable.bd),
    KwikCountryInfo("Barbados", KwikCountry.BB, "+1", flag = R.drawable.bb),
    KwikCountryInfo("Belarus", KwikCountry.BY, "+375", flag = R.drawable.by),
    KwikCountryInfo("Belgium", KwikCountry.BE, "+32", flag = R.drawable.be),
    KwikCountryInfo("Belize", KwikCountry.BZ, "+501", flag = R.drawable.bz),
    KwikCountryInfo("Benin", KwikCountry.BJ, "+229", flag = R.drawable.bj),
    KwikCountryInfo("Bermuda", KwikCountry.BM, "+1", flag = R.drawable.bm),
    KwikCountryInfo("Bhutan", KwikCountry.BT, "+975", flag = R.drawable.bt),
    KwikCountryInfo("Bolivia", KwikCountry.BO, "+591", flag = R.drawable.bo),
    KwikCountryInfo("Bosnia and Herzegovina", KwikCountry.BA, "+387", flag = R.drawable.ba),
    KwikCountryInfo("Botswana", KwikCountry.BW, "+267", flag = R.drawable.bw),
    KwikCountryInfo("Bouvet Island", KwikCountry.BV, "+47", flag = R.drawable.bv),
    KwikCountryInfo("Brazil", KwikCountry.BR, "+55", flag = R.drawable.br),
    KwikCountryInfo("British Indian Ocean Territory", KwikCountry.IO, "+246", flag = R.drawable.io, tags = listOf("Chagos Islands")),
    KwikCountryInfo("Brunei", KwikCountry.BN, "+673", flag = R.drawable.bn),
    KwikCountryInfo("Bulgaria", KwikCountry.BG, "+359", flag = R.drawable.bg),
    KwikCountryInfo("Burkina Faso", KwikCountry.BF, "+226", flag = R.drawable.bf),
    KwikCountryInfo("Burundi", KwikCountry.BI, "+257", flag = R.drawable.bi),
    KwikCountryInfo("Cambodia", KwikCountry.KH, "+855", flag = R.drawable.kh),
    KwikCountryInfo("Cameroon", KwikCountry.CM, "+237", flag = R.drawable.cm),
    KwikCountryInfo("Canada", KwikCountry.CA, "+1", flag = R.drawable.ca),
    KwikCountryInfo("Cape Verde", KwikCountry.CV, "+238", flag = R.drawable.cv),
    KwikCountryInfo("Cayman Islands", KwikCountry.KY, "+1", flag = R.drawable.ky),
    KwikCountryInfo("Central African Republic", KwikCountry.CF, "+236", flag = R.drawable.cf, tags = listOf("CAR")),
    KwikCountryInfo("Chad", KwikCountry.TD, "+235", flag = R.drawable.td),
    KwikCountryInfo("Chile", KwikCountry.CL, "+56", flag = R.drawable.cl),
    KwikCountryInfo("China", KwikCountry.CN, "+86", flag = R.drawable.cn),
    KwikCountryInfo("Christmas Island", KwikCountry.CX, "+61", flag = R.drawable.cx),
    KwikCountryInfo("Cocos (Keeling) Islands", KwikCountry.CC, "+61", flag = R.drawable.cc),
    KwikCountryInfo("Colombia", KwikCountry.CO, "+57", flag = R.drawable.co),
    KwikCountryInfo("Comoros", KwikCountry.KM, "+269", flag = R.drawable.km),
    KwikCountryInfo("Congo, The Republic of the", KwikCountry.CG, "+242", flag = R.drawable.cg, tags = listOf("Brazzaville")),
    KwikCountryInfo("Congo, The Democratic Republic of the", KwikCountry.CD, "+243", flag = R.drawable.cd, tags = listOf("DRC", "Kinshasa")),
    KwikCountryInfo("Cook Islands", KwikCountry.CK, "+682", flag = R.drawable.ck),
    KwikCountryInfo("Costa Rica", KwikCountry.CR, "+506", flag = R.drawable.cr),
    KwikCountryInfo("Croatia", KwikCountry.HR, "+385", flag = R.drawable.hr),
    KwikCountryInfo("Cuba", KwikCountry.CU, "+53", flag = R.drawable.cu),
    KwikCountryInfo("Cyprus", KwikCountry.CY, "+357", flag = R.drawable.cy),
    KwikCountryInfo("Czech Republic", KwikCountry.CZ, "+420", flag = R.drawable.cz),
    KwikCountryInfo("Denmark", KwikCountry.DK, "+45", flag = R.drawable.dk),
    KwikCountryInfo("Djibouti", KwikCountry.DJ, "+253", flag = R.drawable.dj),
    KwikCountryInfo("Dominica", KwikCountry.DM, "+1", flag = R.drawable.dm),
    KwikCountryInfo("Dominican Republic", KwikCountry.DO, "+1", flag = R.drawable.do_),
    KwikCountryInfo("Ecuador", KwikCountry.EC, "+593", flag = R.drawable.ec),
    KwikCountryInfo("Egypt", KwikCountry.EG, "+20", flag = R.drawable.eg),
    KwikCountryInfo("El Salvador", KwikCountry.SV, "+503", flag = R.drawable.sv),
    KwikCountryInfo("Equatorial Guinea", KwikCountry.GQ, "+240", flag = R.drawable.gq),
    KwikCountryInfo("Eritrea", KwikCountry.ER, "+291", flag = R.drawable.er),
    KwikCountryInfo("Estonia", KwikCountry.EE, "+372", flag = R.drawable.ee),
    KwikCountryInfo("eSwatini", KwikCountry.SZ, "+268", flag = R.drawable.sz),
    KwikCountryInfo("Ethiopia", KwikCountry.ET, "+251", flag = R.drawable.et),
    KwikCountryInfo("Falkland Islands (Malvinas)", KwikCountry.FK, "+500", flag = R.drawable.fk),
    KwikCountryInfo("Faroe Islands", KwikCountry.FO, "+298", flag = R.drawable.fo),
    KwikCountryInfo("Fiji", KwikCountry.FJ, "+679", flag = R.drawable.fj),
    KwikCountryInfo("Finland", KwikCountry.FI, "+358", flag = R.drawable.fi),
    KwikCountryInfo("France", KwikCountry.FR, "+33", flag = R.drawable.fr),
    KwikCountryInfo("French Guiana", KwikCountry.GF, "+594", flag = R.drawable.gf),
    KwikCountryInfo("French Polynesia", KwikCountry.PF, "+689", flag = R.drawable.pf),
    KwikCountryInfo("French Southern Territories", KwikCountry.TF, "+262", flag = R.drawable.tf),
    KwikCountryInfo("Gabon", KwikCountry.GA, "+241", flag = R.drawable.ga),
    KwikCountryInfo("Gambia", KwikCountry.GM, "+220", flag = R.drawable.gm),
    KwikCountryInfo("Georgia", KwikCountry.GE, "+995", flag = R.drawable.ge),
    KwikCountryInfo("Germany", KwikCountry.DE, "+49", flag = R.drawable.de, tags = listOf("Deutschland", "Federal Republic of Germany")),
    KwikCountryInfo("Ghana", KwikCountry.GH, "+233", flag = R.drawable.gh),
    KwikCountryInfo("Gibraltar", KwikCountry.GI, "+350", flag = R.drawable.gi),
    KwikCountryInfo("Greece", KwikCountry.GR, "+30", flag = R.drawable.gr),
    KwikCountryInfo("Greenland", KwikCountry.GL, "+299", flag = R.drawable.gl),
    KwikCountryInfo("Grenada", KwikCountry.GD, "+1", flag = R.drawable.gd),
    KwikCountryInfo("Guadeloupe", KwikCountry.GP, "+590", flag = R.drawable.gp),
    KwikCountryInfo("Guam", KwikCountry.GU, "+1", flag = R.drawable.gu),
    KwikCountryInfo("Guatemala", KwikCountry.GT, "+502", flag = R.drawable.gt),
    KwikCountryInfo("Guernsey", KwikCountry.GG, "+44", flag = R.drawable.gg),
    KwikCountryInfo("Guinea", KwikCountry.GN, "+224", flag = R.drawable.gn),
    KwikCountryInfo("Guinea-Bissau", KwikCountry.GW, "+245", flag = R.drawable.gw),
    KwikCountryInfo("Guyana", KwikCountry.GY, "+592", flag = R.drawable.gy),
    KwikCountryInfo("Haiti", KwikCountry.HT, "+509", flag = R.drawable.ht),
    KwikCountryInfo("Heard Island and Mcdonald Islands", KwikCountry.HM, "+672", flag = R.drawable.hm),
    KwikCountryInfo("Honduras", KwikCountry.HN, "+504", flag = R.drawable.hn),
    KwikCountryInfo("Hong Kong", KwikCountry.HK, "+852", flag = R.drawable.hk),
    KwikCountryInfo("Hungary", KwikCountry.HU, "+36", flag = R.drawable.hu),
    KwikCountryInfo("Iceland", KwikCountry.IS, "+354", flag = R.drawable.`is`),
    KwikCountryInfo("India", KwikCountry.IN, "+91", flag = R.drawable.`in`),
    KwikCountryInfo("Indonesia", KwikCountry.ID, "+62", flag = R.drawable.id),
    KwikCountryInfo("Iran", KwikCountry.IR, "+98", flag = R.drawable.ir),
    KwikCountryInfo("Iraq", KwikCountry.IQ, "+964", flag = R.drawable.iq),
    KwikCountryInfo("Ireland", KwikCountry.IE, "+353", flag = R.drawable.ie),
    KwikCountryInfo("Isle of Man", KwikCountry.IM, "+44", flag = R.drawable.im),
    KwikCountryInfo("Israel", KwikCountry.IL, "+972", flag = R.drawable.il),
    KwikCountryInfo("Italy", KwikCountry.IT, "+39", flag = R.drawable.it),
    KwikCountryInfo("Jamaica", KwikCountry.JM, "+1", flag = R.drawable.jm),
    KwikCountryInfo("Japan", KwikCountry.JP, "+81", flag = R.drawable.jp),
    KwikCountryInfo("Jersey", KwikCountry.JE, "+44", flag = R.drawable.je),
    KwikCountryInfo("Jordan", KwikCountry.JO, "+962", flag = R.drawable.jo),
    KwikCountryInfo("Kazakhstan", KwikCountry.KZ, "+7", flag = R.drawable.kz),
    KwikCountryInfo("Kenya", KwikCountry.KE, "+254", flag = R.drawable.ke),
    KwikCountryInfo("Kiribati", KwikCountry.KI, "+686", flag = R.drawable.ki),
    KwikCountryInfo("Korea, Democratic People's Republic of", KwikCountry.KP, "+850", flag = R.drawable.kp, tags = listOf("North Korea", "DPRK")),
    KwikCountryInfo("Korea, Republic of", KwikCountry.KR, "+82", flag = R.drawable.kr, tags = listOf("South Korea", "ROK")),
    KwikCountryInfo("Kuwait", KwikCountry.KW, "+965", flag = R.drawable.kw),
    KwikCountryInfo("Kyrgyzstan", KwikCountry.KG, "+996", flag = R.drawable.kg),
    KwikCountryInfo("Lao People's Democratic Republic", KwikCountry.LA, "+856", flag = R.drawable.la, tags = listOf("Laos")),
    KwikCountryInfo("Latvia", KwikCountry.LV, "+371", flag = R.drawable.lv),
    KwikCountryInfo("Lebanon", KwikCountry.LB, "+961", flag = R.drawable.lb),
    KwikCountryInfo("Lesotho", KwikCountry.LS, "+266", flag = R.drawable.ls),
    KwikCountryInfo("Liberia", KwikCountry.LR, "+231", flag = R.drawable.lr),
    KwikCountryInfo("Libyan Arab Jamahiriya", KwikCountry.LY, "+218", flag = R.drawable.ly, tags = listOf("Libya")),
    KwikCountryInfo("Liechtenstein", KwikCountry.LI, "+423", flag = R.drawable.li),
    KwikCountryInfo("Lithuania", KwikCountry.LT, "+370", flag = R.drawable.lt),
    KwikCountryInfo("Luxembourg", KwikCountry.LU, "+352", flag = R.drawable.lu),
    KwikCountryInfo("Macao", KwikCountry.MO, "+853", flag = R.drawable.mo),
    KwikCountryInfo("Macedonia", KwikCountry.MK, "+389", flag = R.drawable.mk),
    KwikCountryInfo("Madagascar", KwikCountry.MG, "+261", flag = R.drawable.mg),
    KwikCountryInfo("Malawi", KwikCountry.MW, "+265", flag = R.drawable.mw),
    KwikCountryInfo("Malaysia", KwikCountry.MY, "+60", flag = R.drawable.my),
    KwikCountryInfo("Maldives", KwikCountry.MV, "+960", flag = R.drawable.mv),
    KwikCountryInfo("Mali", KwikCountry.ML, "+223", flag = R.drawable.ml),
    KwikCountryInfo("Malta", KwikCountry.MT, "+356", flag = R.drawable.mt),
    KwikCountryInfo("Marshall Islands", KwikCountry.MH, "+692", flag = R.drawable.mh),
    KwikCountryInfo("Martinique", KwikCountry.MQ, "+596", flag = R.drawable.mq),
    KwikCountryInfo("Mauritania", KwikCountry.MR, "+222", flag = R.drawable.mr),
    KwikCountryInfo("Mauritius", KwikCountry.MU, "+230", flag = R.drawable.mu),
    KwikCountryInfo("Mayotte", KwikCountry.YT, "+262", flag = R.drawable.yt),
    KwikCountryInfo("Mexico", KwikCountry.MX, "+52", flag = R.drawable.mx),
    KwikCountryInfo("Micronesia", KwikCountry.FM, "+691", flag = R.drawable.fm),
    KwikCountryInfo("Moldova", KwikCountry.MD, "+373", flag = R.drawable.md),
    KwikCountryInfo("Monaco", KwikCountry.MC, "+377", flag = R.drawable.mc),
    KwikCountryInfo("Mongolia", KwikCountry.MN, "+976", flag = R.drawable.mn),
    KwikCountryInfo("Montenegro", KwikCountry.ME, "+382", flag = R.drawable.me),
    KwikCountryInfo("Montserrat", KwikCountry.MS, "+1", flag = R.drawable.ms),
    KwikCountryInfo("Morocco", KwikCountry.MA, "+212", flag = R.drawable.ma),
    KwikCountryInfo("Mozambique", KwikCountry.MZ, "+258", flag = R.drawable.mz),
    KwikCountryInfo("Myanmar", KwikCountry.MM, "+95", flag = R.drawable.mm),
    KwikCountryInfo("Namibia", KwikCountry.NA, "+264", flag = R.drawable.na),
    KwikCountryInfo("Nauru", KwikCountry.NR, "+674", flag = R.drawable.nr),
    KwikCountryInfo("Nepal", KwikCountry.NP, "+977", flag = R.drawable.np),
    KwikCountryInfo("Netherlands", KwikCountry.NL, "+31", flag = R.drawable.nl, tags = listOf("Holland")),
    KwikCountryInfo("Netherlands Antilles", KwikCountry.AN, "+599", flag = R.drawable.an, tags = listOf("Curacao", "Bonaire", "Saba", "Sint Maarten", "Sint Eustatius")),
    KwikCountryInfo("New Caledonia", KwikCountry.NC, "+687", flag = R.drawable.nc),
    KwikCountryInfo("New Zealand", KwikCountry.NZ, "+64", flag = R.drawable.nz),
    KwikCountryInfo("Nicaragua", KwikCountry.NI, "+505", flag = R.drawable.ni),
    KwikCountryInfo("Niger", KwikCountry.NE, "+227", flag = R.drawable.ne),
    KwikCountryInfo("Nigeria", KwikCountry.NG, "+234", flag = R.drawable.ng),
    KwikCountryInfo("Niue", KwikCountry.NU, "+683", flag = R.drawable.nu),
    KwikCountryInfo("Norfolk Island", KwikCountry.NF, "+672", flag = R.drawable.nf),
    KwikCountryInfo("Northern Mariana Islands", KwikCountry.MP, "+1", flag = R.drawable.mp),
    KwikCountryInfo("Norway", KwikCountry.NO, "+47", flag = R.drawable.no),
    KwikCountryInfo("Oman", KwikCountry.OM, "+968", flag = R.drawable.om),
    KwikCountryInfo("Pakistan", KwikCountry.PK, "+92", flag = R.drawable.pk),
    KwikCountryInfo("Palau", KwikCountry.PW, "+680", flag = R.drawable.pw),
    KwikCountryInfo("Palestine", KwikCountry.PS, "+970", flag = R.drawable.ps),
    KwikCountryInfo("Panama", KwikCountry.PA, "+507", flag = R.drawable.pa),
    KwikCountryInfo("Papua New Guinea", KwikCountry.PG, "+675", flag = R.drawable.pg),
    KwikCountryInfo("Paraguay", KwikCountry.PY, "+595", flag = R.drawable.py),
    KwikCountryInfo("Peru", KwikCountry.PE, "+51", flag = R.drawable.pe),
    KwikCountryInfo("Philippines", KwikCountry.PH, "+63", flag = R.drawable.ph),
    KwikCountryInfo("Pitcairn", KwikCountry.PN, "+870", flag = R.drawable.pn),
    KwikCountryInfo("Poland", KwikCountry.PL, "+48", flag = R.drawable.pl),
    KwikCountryInfo("Portugal", KwikCountry.PT, "+351", flag = R.drawable.pt),
    KwikCountryInfo("Puerto Rico", KwikCountry.PR, "+1", flag = R.drawable.pr),
    KwikCountryInfo("Qatar", KwikCountry.QA, "+974", flag = R.drawable.qa),
    KwikCountryInfo("Reunion", KwikCountry.RE, "+262", flag = R.drawable.re),
    KwikCountryInfo("Romania", KwikCountry.RO, "+40", flag = R.drawable.ro),
    KwikCountryInfo("Russian Federation", KwikCountry.RU, "+7", flag = R.drawable.ru),
    KwikCountryInfo("Rwanda", KwikCountry.RW, "+250", flag = R.drawable.rw, tags = listOf("Kigali")),
    KwikCountryInfo("Saint Helena", KwikCountry.SH, "+290", flag = R.drawable.sh),
    KwikCountryInfo("Saint Kitts and Nevis", KwikCountry.KN, "+1", flag = R.drawable.kn),
    KwikCountryInfo("Saint Lucia", KwikCountry.LC, "+1", flag = R.drawable.lc),
    KwikCountryInfo("Saint Pierre and Miquelon", KwikCountry.PM, "+508", flag = R.drawable.pm, tags = listOf("St. Pierre and Miquelon")),
    KwikCountryInfo("Saint Vincent and the Grenadines", KwikCountry.VC, "+1", flag = R.drawable.vc, tags = listOf("St. Vincent and the Grenadines")),
    KwikCountryInfo("Samoa", KwikCountry.WS, "+685", flag = R.drawable.ws),
    KwikCountryInfo("San Marino", KwikCountry.SM, "+378", flag = R.drawable.sm),
    KwikCountryInfo("Sao Tome and Principe", KwikCountry.ST, "+239", flag = R.drawable.st, tags = listOf("São Tomé and Príncipe")),
    KwikCountryInfo("Saudi Arabia", KwikCountry.SA, "+966", flag = R.drawable.sa, tags = listOf("KSA", "Kingdom of Saudi Arabia")),
    KwikCountryInfo("Senegal", KwikCountry.SN, "+221", flag = R.drawable.sn),
    KwikCountryInfo("Serbia", KwikCountry.RS, "+381", flag = R.drawable.rs),
    KwikCountryInfo("Seychelles", KwikCountry.SC, "+248", flag = R.drawable.sc),
    KwikCountryInfo("Sierra Leone", KwikCountry.SL, "+232", flag = R.drawable.sl),
    KwikCountryInfo("Singapore", KwikCountry.SG, "+65", flag = R.drawable.sg),
    KwikCountryInfo("Slovakia", KwikCountry.SK, "+421", flag = R.drawable.sk),
    KwikCountryInfo("Slovenia", KwikCountry.SI, "+386", flag = R.drawable.si),
    KwikCountryInfo("Solomon Islands", KwikCountry.SB, "+677", flag = R.drawable.sb),
    KwikCountryInfo("Somalia", KwikCountry.SO, "+252", flag = R.drawable.so),
    KwikCountryInfo("South Africa", KwikCountry.ZA, "+27", flag = R.drawable.za),
    KwikCountryInfo("South Sudan", KwikCountry.SS, "+211", flag = R.drawable.ss),
    KwikCountryInfo("Spain", KwikCountry.ES, "+34", flag = R.drawable.es),
    KwikCountryInfo("Sri Lanka", KwikCountry.LK, "+94", flag = R.drawable.lk, tags = listOf("Ceylon")),
    KwikCountryInfo("Sudan", KwikCountry.SD, "+249", flag = R.drawable.sd),
    KwikCountryInfo("Suriname", KwikCountry.SR, "+597", flag = R.drawable.sr),
    KwikCountryInfo("Sweden", KwikCountry.SE, "+46", flag = R.drawable.se, tags = listOf("Sverige")),
    KwikCountryInfo("Switzerland", KwikCountry.CH, "+41", flag = R.drawable.ch, tags = listOf("Swiss Confederation")),
    KwikCountryInfo("Syria", KwikCountry.SY, "+963", flag = R.drawable.sy),
    KwikCountryInfo("Taiwan", KwikCountry.TW, "+886", flag = R.drawable.tw),
    KwikCountryInfo("Tajikistan", KwikCountry.TJ, "+992", flag = R.drawable.tj),
    KwikCountryInfo("Tanzania, United Republic of", KwikCountry.TZ, "+255", flag = R.drawable.tz, tags = listOf("Zanzibar", "Tanganyika")),
    KwikCountryInfo("Thailand", KwikCountry.TH, "+66", flag = R.drawable.th),
    KwikCountryInfo("Timor-Leste", KwikCountry.TL, "+670", flag = R.drawable.tl),
    KwikCountryInfo("Togo", KwikCountry.TG, "+228", flag = R.drawable.tg),
    KwikCountryInfo("Tokelau", KwikCountry.TK, "+690", flag = R.drawable.tk),
    KwikCountryInfo("Tonga", KwikCountry.TO, "+676", flag = R.drawable.to),
    KwikCountryInfo("Trinidad and Tobago", KwikCountry.TT, "+1", flag = R.drawable.tt),
    KwikCountryInfo("Tunisia", KwikCountry.TN, "+216", flag = R.drawable.tn),
    KwikCountryInfo("Turkey", KwikCountry.TR, "+90", flag = R.drawable.tr),
    KwikCountryInfo("Turkmenistan", KwikCountry.TM, "+993", flag = R.drawable.tm),
    KwikCountryInfo("Turks and Caicos Islands", KwikCountry.TC, "+1", flag = R.drawable.tc),
    KwikCountryInfo("Tuvalu", KwikCountry.TV, "+688", flag = R.drawable.tv),
    KwikCountryInfo("Uganda", KwikCountry.UG, "+256", flag = R.drawable.ug),
    KwikCountryInfo("Ukraine", KwikCountry.UA, "+380", flag = R.drawable.ua),
    KwikCountryInfo("United Arab Emirates", KwikCountry.AE, "+971", flag = R.drawable.ae, tags = listOf("UAE", "Emirates", "Dubai", "Abu Dhabi")),
    KwikCountryInfo("United Kingdom", KwikCountry.GB, "+44", flag = R.drawable.gb, tags = listOf("UK", "GB")),
    KwikCountryInfo("United States", KwikCountry.US, "+1", flag = R.drawable.us, tags = listOf("USA", "US", "America")),
    KwikCountryInfo("Uruguay", KwikCountry.UY, "+598", flag = R.drawable.uy),
    KwikCountryInfo("Uzbekistan", KwikCountry.UZ, "+998", flag = R.drawable.uz),
    KwikCountryInfo("Vanuatu", KwikCountry.VU, "+678", flag = R.drawable.vu),
    KwikCountryInfo("Vatican", KwikCountry.VA, "+379", flag = R.drawable.va),
    KwikCountryInfo("Venezuela", KwikCountry.VE, "+58", flag = R.drawable.ve),
    KwikCountryInfo("Vietnam", KwikCountry.VN, "+84", flag = R.drawable.vn),
    KwikCountryInfo("Virgin Islands, British", KwikCountry.VG, "+1", flag = R.drawable.vg),
    KwikCountryInfo("Virgin Islands, U.S.", KwikCountry.VI, "+1", flag = R.drawable.vi),
    KwikCountryInfo("Wallis and Futuna", KwikCountry.WF, "+681", flag = R.drawable.wf),
    KwikCountryInfo("Western Sahara", KwikCountry.EH, "+212", flag = R.drawable.eh),
    KwikCountryInfo("Yemen", KwikCountry.YE, "+967", flag = R.drawable.ye),
    KwikCountryInfo("Zambia", KwikCountry.ZM, "+260", flag = R.drawable.zm),
    KwikCountryInfo("Zimbabwe", KwikCountry.ZW, "+263", flag = R.drawable.zw)
)

enum class KwikCountry {
    AF,
    AX,
    AL,
    DZ,
    AS,
    AD,
    AO,
    AI,
    AQ,
    AG,
    AR,
    AM,
    AW,
    AU,
    AT,
    AZ,
    BS,
    BH,
    BD,
    BB,
    BY,
    BE,
    BZ,
    BJ,
    BM,
    BT,
    BO,
    BA,
    BW,
    BV,
    BR,
    IO,
    BN,
    BG,
    BF,
    BI,
    KH,
    CM,
    CA,
    CV,
    KY,
    CF,
    TD,
    CL,
    CN,
    CX,
    CC,
    CO,
    KM,
    CG,
    CD,
    CK,
    CR,
    HR,
    CU,
    CY,
    CZ,
    DK,
    DJ,
    DM,
    DO,
    EC,
    EG,
    SV,
    GQ,
    ER,
    EE,
    SZ,
    ET,
    FK,
    FO,
    FJ,
    FI,
    FR,
    GF,
    PF,
    TF,
    GA,
    GM,
    GE,
    DE,
    GH,
    GI,
    GR,
    GL,
    GD,
    GP,
    GU,
    GT,
    GG,
    GN,
    GW,
    GY,
    HT,
    HM,
    HN,
    HK,
    HU,
    IS,
    IN,
    ID,
    IR,
    IQ,
    IE,
    IM,
    IL,
    IT,
    JM,
    JP,
    JE,
    JO,
    KZ,
    KE,
    KI,
    KP,
    KR,
    KW,
    KG,
    LA,
    LV,
    LB,
    LS,
    LR,
    LY,
    LI,
    LT,
    LU,
    MO,
    MK,
    MG,
    MW,
    MY,
    MV,
    ML,
    MT,
    MH,
    MQ,
    MR,
    MU,
    YT,
    MX,
    FM,
    MD,
    MC,
    MN,
    ME,
    MS,
    MA,
    MZ,
    MM,
    NA,
    NR,
    NP,
    NL,
    AN,
    NC,
    NZ,
    NI,
    NE,
    NG,
    NU,
    NF,
    MP,
    NO,
    OM,
    PK,
    PW,
    PS,
    PA,
    PG,
    PY,
    PE,
    PH,
    PN,
    PL,
    PT,
    PR,
    QA,
    RE,
    RO,
    RU,
    RW,
    SH,
    KN,
    LC,
    PM,
    VC,
    WS,
    SM,
    ST,
    SA,
    SN,
    RS,
    SC,
    SL,
    SG,
    SK,
    SI,
    SB,
    SO,
    ZA,
    ES,
    LK,
    SD,
    SR,
    SS,
    SE,
    CH,
    SY,
    TW,
    TJ,
    TZ,
    TH,
    TL,
    TG,
    TK,
    TO,
    TT,
    TN,
    TR,
    TM,
    TC,
    TV,
    UG,
    UA,
    AE,
    GB,
    US,
    UY,
    UZ,
    VU,
    VA,
    VE,
    VN,
    VG,
    VI,
    WF,
    EH,
    YE,
    ZM,
    ZW
}

/**
 * Allows you to filter the list of countries by including only the countries you want
 * Note that includeOnly takes precedence over omit
 * @param includeOnly a list of country codes to include.
 * @param omit a list of country codes to omit.
 *
 * Usage example:
 *
 * ```
 * val countries = resolveCountries(
 *     includeOnly = listOf(KwikCountry.RW, KwikCountry.KE),
 *     omit = listOf(KwikCountry.XX)
 * )
 * ```
 * */
fun resolveCountries(
    includeOnly: List<KwikCountry> = listOf(),
    omit: List<KwikCountry> = listOf(),
): List<KwikCountryInfo> {
    if(includeOnly.isNotEmpty()) return countryList.filter { country -> includeOnly.contains(country.code) }
    if(omit.isNotEmpty()) countryList.filter { country -> !omit.contains(country.code) }
    return countryList
}

internal fun getCountryInfo(code: KwikCountry): KwikCountryInfo? {
    return countryList.firstOrNull { it.code == code }
}

/*
* name = country name
* code = country code
* dialingCode = country dialing code
* flag = country flag
* for example, Dominican Republic has a country code of DO but the drawable code is DO_O because DO is a reserved keyword
* */
data class KwikCountryInfo(val name: String, val code: KwikCountry, val dialingCode: String, @DrawableRes val flag: Int, val tags: List<String> = listOf())

/**
 * Utility function to get the country code of the device based on the network country ISO
 * This function uses the TelephonyManager to get the network country ISO and returns the corresponding [KwikCountry], which is an ISO 3166-1 alpha-2 code.
 * */
fun Context.countryCode(): KwikCountry {
    val telephonyManager = this.getSystemService(TELEPHONY_SERVICE) as TelephonyManager
    return try {
        val countryCode = telephonyManager.networkCountryIso.uppercase(Locale.ROOT)
        KwikCountry.valueOf(countryCode)
    } catch (e: Exception) {
        KwikCountry.RW
    }
}
